CookBook/Controllers/ApiController.cs
using Context;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CookBook.Controllers {
    [Route("[controller]")]
    [ApiController]
    public class ApiController : ControllerBase {
        Connection Connection { get; set; } = new Connection(Startup.Configuration["ConnectionStrings:Default"]);
        [HttpGet]
        [Route("GetRecipts")]
        public IActionResult GetRecipts(int id = -1) {
            if (id == -1)
                return Ok(Connection.Recipts.ToList());
            else {
                var result = Connection.Recipts.FirstOrDefault(x => x.Id == id);
                if (result != null)
                    return Ok(result);
                else
                    return NotFound();
            }
        }
    }
}

CookBook/Controllers/IndexController.cs
using Context;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CookBook.Controllers {
    [Route("api/[controller]")]
    [ApiController]
    public class IndexController : ControllerBase {
        Connection Connection { get; set; } = new Connection(Startup.Configuration["ConnectionStrings:Default"]);
        [HttpPost]
        [Route("GetRecipts")]
        public IActionResult GetRecipts(int id = -1) {
            if (id == -1)
                return Ok(Connection.Recipts
                    .Include(x => x.Ingredients)
                        .ThenInclude(ingredient => ingredient.Products)
                        .ThenInclude(unit => unit.Units)
                    .Include(x => x.Reviews)
                        .ThenInclude(x => x.User)
                    .ToList());
            else {
                var results = Connection.Recipts.Where(x => x.RecCategoryId == id)
                    .Include(x => x.Ingredients)
                        .ThenInclude(ingredient => ingredient.Products)
                        .ThenInclude(unit => unit.Units)
                    .Include(x => x.Reviews)
                        .ThenInclude(x => x.User)
                    .ToList();
                if (results.Count == 0)
                    return NotFound(results);
                return Ok(results);
            }
        }
    }
}

CookBook/Controllers/LoginController.cs
using Context;
using Context.Model;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CookBook.Controllers {
    [Route("[controller]")]
    public class LoginController : Controller {
        Connection Connection { get; set; } = new Connection(Startup.Configuration["ConnectionStrings:Default"]);
        [HttpGet]
        public IActionResult Authorization() {
            return View();
        }
        [Route("Authorization")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Authorization(User userdata) {
            if (userdata.UsLogin == null || userdata.UsPassword == null)
                return Redirect("/login");
            var user = Connection.User.FirstOrDefault(x => x.UsLogin.ToLower() == userdata.UsLogin.ToLower() && x.UsPassword.ToLower() == userdata.UsPassword.ToLower());
            if (user == null)
                return Redirect("/login");

            var claims = new List<Claim>{
                new Claim(ClaimsIdentity.DefaultNameClaimType, user.UsLogin)
            };
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
            return Redirect("/");
        }
        [Route("Logout")]
        [HttpPost]
        public async Task<IActionResult> Logout() {
            try {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch { }
            return Redirect("/login");
        }
    }
}

CookBook/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Context;
using Context.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CookBook.Pages {
    public class IndexModel : PageModel {
        public Connection Connection { get; set; } = new Connection(Startup.Configuration["ConnectionStrings:Default"]);
        public void OnGet() {
        }
        public void OnPostSendComment(int reciptsId = -1, string comments = null, short rating = -1) {
            var user = User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;
            if (comments == null && rating == -1 || user == null)
                return;
            Connection.Reviews.Add(new Reviews() {
                RevMessage = comments,
                RevRating = rating,
                ReciptsId = reciptsId,
                UserId = Connection.User.FirstOrDefault(x => x.UsLogin == user).Id,
                RevDate = DateTime.Now,
            });
            Connection.SaveChanges();
        }
    }
}

CookBook/Pages/Index.cshtml
@page
@model CookBook.Pages.IndexModel
@using Microsoft.EntityFrameworkCore;
@using CookBook.Controllers;
@using Newtonsoft.Json;
@using System.Security.Claims;
@{
    ViewData["Title"] = "Каталог";
}
<div class="row container">
    <div class="col-lg-9">
        <div class="card" id="card">

        </div>
    </div>
    <div class="col col-lg-3">
        <div class="form-group">
            <select class="custom-select" required onchange="SelectCategory(this.options[this.selectedIndex].value)">
                <option value="-1">Все сразу</option>
                @foreach (var category in Model.Connection.Categories) {
                    <option value="@category.Id">@category.CategoryName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <select class="custom-select" id="recipt" required onchange="SelectRecipt(this.options[this.selectedIndex].value)">
            </select>
        </div>
        @if (User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value != null) {
            <div class="card">
                <div class="card-header">
                    Оставить коментарий
                </div>
                <form method="POST">
                    <div class="card-body">
                        <div class="form-group">
                            <input type="number" class="form-control" name="reciptsId" id="reciptsId" placeholder="Коментарий" value="4" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="comments" placeholder="Коментарий"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="number" min="1" max="5" class="form-control" name="rating" placeholder="рейтинг" />
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <input type="submit" class="btn btn-primary" asp-page-handler="SendComment" value="Отправить коментарий" />
                    </div>
                </form>
            </div>
        }
    </div>
</div>
<script id="data">
</script>
<style>
    .container {
        max-width: 1500px;
        margin: auto;
    }
</style>

CookBook/Pages/Shared/_Layout.cshtml
@using System.Security.Claims;
@{
    var user = User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Книга Рецептов</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link @(ViewData["Title"] == "Каталог" ? "active" : null)" href="/">Каталог</a>
                <a class="nav-item nav-link @(ViewData["Title"] == "О нас" ? "active" : null)" href="/AboutUs">О нас</a>
                @if (user == null) {
                    <a class="nav-item nav-link @(ViewData["Title"] == "Авторизация" ? "active" : null)" href="/Login">Вход</a>
                }
                else {
                    <form asp-action="Logout" asp-controller="Login">
                        <input type="submit" class="nav-item nav-link" value="Выход" />
                    </form>
                }
            </div>
        </div>
    </nav>
    @RenderBody()
    <script src="/js/My.js"></script>
</body>
</html>

CookBook/Views/Login/Authorization.cshtml
@model Context.Model.User
@{
    ViewData["Title"] = "Авторизация";
}
<container>
    <div class="row justify-content-md-center">
        <div class="col col-lg-2">
            <form asp-action="Authorization" asp-controller="Login" asp-antiforgery="true">
                <div class="form-group">
                    <input type="text" asp-for="UsLogin" placeholder="Логин" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="password" asp-for="UsPassword" placeholder="Пароль" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Вход" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</container>